services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      api:
        condition: service_healthy
      - db

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 10s
      retries: 5

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_v6:/var/lib/postgresql/data
      - ./export.pgsql:/export.pgsql
      - ./load-dbdata.sh:/load-dbdata.sh

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front
      - api

volumes:
   postgres_data_v6:

  
  

      
