services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_v6:/var/lib/postgresql/data
      - ./export.pgsql:/export.pgsql
      - ./load-dbdata.sh:/load-dbdata.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s        
      timeout: 10s         
      retries: 5           
      start_period: 5s    

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - front
      - api

volumes:
   postgres_data_v6:

  
  

      
