# Generated by Django 5.1 on 2024-09-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Voiture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immat", models.CharField(max_length=9)),
                ("color", models.CharField(max_length=30)),
                ("marque", models.CharField(max_length=30)),
                ("modele", models.CharField(max_length=30)),
                (
                    "garage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.garage"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("etat_pret", models.BooleanField()),
                ("date_pret", models.DateField(blank=True, null=True)),
                ("date_rendu", models.DateField(blank=True, null=True)),
                (
                    "voiture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.voiture"
                    ),
                ),
            ],
        ),
    ]
