# Generated by Django 5.1 on 2024-09-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="voiture",
            name="photo",
            field=models.ImageField(default=1, upload_to="cars"),
            preserve_default=False,
        ),
    ]
