# Generated by Django 5.1 on 2024-09-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_voiture_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="garage",
            name="adresse",
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
