# Generated by Django 5.1 on 2024-09-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_garage_adresse"),
    ]

    operations = [
        migrations.AddField(
            model_name="garage",
            name="code_postal",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
