# Generated by Django 4.2.16 on 2024-09-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_garage_code_postal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cle',
            name='date_pret',
        ),
        migrations.RemoveField(
            model_name='cle',
            name='date_rendu',
        ),
        migrations.RemoveField(
            model_name='cle',
            name='etat_pret',
        ),
    ]
